### ISSUE TITLE
перепиши на джаву

### ISSUE THREAD

**Issue by nutrolshok** [fiwka/sosilol#12]
котлин выглядит хуже чем джава, код на котлине хуже чем на джаве. Переписывай.

**Comment by fiwka** [comment]
Не имеет смысла

**Comment by steelswing** [comment]
код хуйня у фишки

**Comment by steelswing** [comment]
код хуйня у фишки

**Comment by steelswing** [comment]
код хуйня у фишки

**Comment by steelswing** [comment]
код хуйня у фишки
